#############################
#
# web访问端口号    约定: 8088
#
############################

server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB


#############################
#
# 配置数据源信息
#
############################
spring:
  datasource:                                        # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource         # 数据源类型: HikariCP
    driver-class-name: com.mysql.jdbc.Driver         # mysql
    url: jdbc:mysql://47.106.215.196:3306/learn_info?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 51577a348533                         #useUnicode=true&characterEncoding=utf-8&useSSL=false
    hikari:
      connection-timeout: 30000                      # 等待连接池分配的最大时长还没可用的连接则发生SQLException,默认30秒
      minimum-idle: 5                                # 最小连接数
      maximum-pool-size: 10                          # 最大连接数
      auto-commit: true                              # 自动提交
      idle-timeout: 600000                           # 连接超时的最大时长(毫秒),超时则释放(retired),默认:10分钟
      pool-name: DataSourceHikariCP                  # 连接池名字
      max-lifetime: 1800000                          # 连接的生命时长(毫秒),超时而且没被使用则释放(retired)，默认:30分钟
      connection-test-query: SELECT 1

#############################
#
# mybatis配置
#
############################

mybatis:
  type-aliases-package: com.boil.pojo
  mapper-locations: classpath:mapper/*.xml

#############################
#
# 通用Mapper配置
#
############################

mapper:
  mappers: com.boil.my.mapper.MyMapper
  not-empty: false           # 在进行数据库操作的时候，判断表达式， username != null,是否追加 username != " "
  identity: MYSQL
